### ISSUE TITLE
Route configuration support

### ISSUE THREAD

**Issue by M0dEx** [M0dEx/quincy#1]
Quincy should support route configuration:
- client-side routes in client configuration
- server-side routes in server configuration
- client-side routes in server configuration sent during authentication

**Comment by M0dEx** [comment]
Looks like [net-route](https://github.com/johnyburd/net-route) could by a nice candidate for a library to set-up routes on commonly-used operation systems.

**Comment by inceabdullah** [comment]
Also add firewall rules on server-side, like netfilter
On the server-side, 
```bash
nft add rule ip filter FORWARD counter accept
nft add rule ip filter FORWARD oifname "<inet iface>" counter accept
```

**inet iface** is interface to connect internet.

----
But I am not sure which crate should be used for binding.

**Comment by M0dEx** [comment]
> Also add firewall rules on server-side, like netfilter On the server-side,
> 
> ```shell
> nft add rule ip filter FORWARD counter accept
> nft add rule ip filter FORWARD oifname "<inet iface>" counter accept
> ```
> 
> **inet iface** is interface to connect internet.
> 
> But I am not sure which crate should be used for binding.
> 
> 1. [nftnl-rs](https://github.com/mullvad/nftnl-rs)

I am tempted to go the way of Wireguard and just allow `PreUp`, `PostUp`, `PreDown` and `PostDown` scripts, which would allow users to set-up routes and what not.

**Comment by inceabdullah** [comment]
I've created a crate (using net-route) that accepts two parameters: 'tun device' and 'connection IP'. Clients can utilize this crate to create a TUN device, for instance, with names like 'tun0' and IP addresses like '1.2.3.4'.

-----

With this crate, you can run a daemon that follows the workflow outlined below:
1. Set a specific route '1.2.3.4/32' as the default route.
2. Replace the default route with the gateway IP of the 'tun0' device.
3. Start listening for changes.
4. If the 'tun0' device disappears or if there are changes in 'tun0'-related routes, the daemon reverts the default route to the old default gateway IP and removes the '1.2.3.4/32' route.

Feel free to check it out: [inceabdullah/tun-route-daemon](https://github.com/inceabdullah/tun-route-daemon)

**Comment by M0dEx** [comment]
> I've created a crate (using net-route) that accepts two parameters: 'tun device' and 'connection IP'. Clients can utilize this crate to create a TUN device, for instance, with names like 'tun0' and IP addresses like '1.2.3.4'.
> 
> With this crate, you can run a daemon that follows the workflow outlined below:
> 
> 1. Set a specific route '1.2.3.4/32' as the default route.
> 2. Replace the default route with the gateway IP of the 'tun0' device.
> 3. Start listening for changes.
> 4. If the 'tun0' device disappears or if there are changes in 'tun0'-related routes, the daemon reverts the default route to the old default gateway IP and removes the '1.2.3.4/32' route.
> 
> Feel free to check it out: [inceabdullah/tun-route-daemon](https://github.com/inceabdullah/tun-route-daemon)

The thing with net-route is that it adds a lot of dependencies, about 50 with the current `Cargo.toml`.
That, together with the added complexity to parse and handle all types of routes, makes me lean towards the way of just allowing users to specify `PreUp`, `PostUp`, `PreDown` and `PostDown` scripts.

**Comment by WyseNynja** [comment]
Until this is automated, what are the steps for setting up routes for quincy? I'm on a mac, but general steps would be helpful, too.

**Comment by M0dEx** [comment]
> Until this is automated, what are the steps for setting up routes for Quincy? I'm on a Mac, but general steps would be helpful, too.
> 
> Also, the tunnel on my system is named "utun4", so we will need to make sure it picks the right one and doesn't just assume "tun0"

Currently, the way to set up routes on MacOS (with the `ip` package installed) and most Linux distributions is this command:
```
$ ip route add <the subnet you want routed> dev <Quincy interface>
$ ip route add 10.0.0.0/24 dev utun4
```

As far as automating this, the library used for TUN interface management (`rust-tun`) provides you with access to the interface properties, including its name. Together with #18, Quincy can broadcast this information to other tools or act on it independently.
