### ISSUE TITLE
A successor to rust-tun can be used now

### ISSUE THREAD

**Issue by xmh0511** [M0dEx/quincy#37]
https://crates.io/crates/tun2 has an improvement to the performance on the Windows platform compared to rust-tun(0.6.1), which is also a successor(a fork) to rust-tun and has actively maintained. Have done a refactor to rust-tun with a tiny original API change. Switch to this actively maintained crate if you would like.

**Comment by xmh0511** [comment]
> The API should be more or less compatible, I pressume.

Yes, The API almost has no change. The most important change is to make the behavior consistent on all platforms. For example, you no longer need to process the packet information delivered from/to `tun2`, the packets just have no extra header on all platforms.

**Comment by M0dEx** [comment]
Migrated in 0.6.0.
