### ISSUE TITLE
(offtopic) Who is responsible for sending an IP packet through a TUN adapter in a point-to-point tunnel? (kernel or programmer/code)?

### ISSUE THREAD

**Issue by vukitoso** [M0dEx/quincy#54]
Hello.
The question is a little off Quincy :)
I want to develop my own solution for organizing a point-to-point VPN tunnel.
Using quincy as an example, a tun adapter is created on Linux and the necessary routes are registered in the routing table.
This allows you to wrap any traffic (TCP/UDP/ICMP) through tun.
The tunnel itself can be on WSS (WebSockets Secure) or on QUIC.

I want to understand one point: who is responsible for working with the IP packet when sending it through the created WSS/QUIC tunnel - the Linux kernel or is it implemented by the programmer in the client/server?

**Comment by M0dEx** [comment]
Moved to #55.
