### ISSUE TITLE
Two clients in the same nat cannot communicate with each other

### ISSUE THREAD

**Issue by xmh0511** [M0dEx/quincy#56]
```  
     Server
       |
       NAT 
     /     \
    /       \
  A           B 
```
In this network structure, `A` and `B` may have the same public `IP` and different `ports`, and `A` cannot successfully send packets to `B` nor vice versa since the `NAT` does not support [NAT_hairpinning](https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning). We may need to make `A` directly send packets to `B` via the local network IP addresses?

**Comment by M0dEx** [comment]
This technically should not be needed, as the traffic will be routed through the server. Since the clients only share the IP, not the socket, the traffic should pass just fine.

However, routing traffic between clients does not work as of now, which seems to be a bug in the server-side implementation: #41.

**Comment by M0dEx** [comment]
@xmh0511 Could you test this with the `client-isolation` branch?
```
cargo install quincy --git https://github.com/M0dEx/quincy.git --branch 'client-isolation'
```

When you set `isolate_clients` in the server config to `false`, you should be able to send traffic between the two clients through the Quincy connection.

**Comment by xmh0511** [comment]
> @xmh0511 Could you test this with the `client-isolation` branch?
> 
> ```
> cargo install quincy --git https://github.com/M0dEx/quincy.git --branch 'client-isolation'
> ```
> 
> When you set `isolate_clients` in the server config to `false`, you should be able to send traffic between the two clients through the Quincy connection.

The client in this branch cannot connect to the server, which reports an error that
> 2024-03-19T06:37:19.832379Z  INFO quincy::client: Connecting: njlsby.cn:8888
2024-03-19T06:37:20.903545Z  INFO quincy::client: Connection established: njlsby.cn:8888
2024-03-19T06:37:20.914164Z ERROR quincy_client: A critical error occurred: authentication failed

However, in the main branch, the connection is Ok
> 2024-03-19T06:37:49.320049Z  INFO quincy::client: Successfully authenticated
2024-03-19T06:37:49.320073Z  INFO quincy::client: Received client address: 10.0.2.2/24

**Comment by xmh0511** [comment]
Update the server side, now, the `quincy-server` reports
>2024-03-19T07:00:54.039046Z ERROR quincy_server: A critical error occurred: missing field `authentication`

**Comment by xmh0511** [comment]
> @xmh0511 Could you test this with the `client-isolation` branch?
> 
> ```
> cargo install quincy --git https://github.com/M0dEx/quincy.git --branch 'client-isolation'
> ```
> 
> When you set `isolate_clients` in the server config to `false`, you should be able to send traffic between the two clients through the Quincy connection.

Running two clients, one is on my macOS, and another is on Windows in my vmware. The windows client can successfully ping the one on macOS, but not vice versa. 

### windows
<img width="969" alt="截屏2024-03-19 15 51 17" src="https://github.com/M0dEx/quincy/assets/17973891/271dbf37-f7de-4b1b-aed0-7a1945d387c8">
<img width="562" alt="截屏2024-03-19 15 51 25" src="https://github.com/M0dEx/quincy/assets/17973891/59979064-0d64-4fe5-a2cf-6756d6115c17">


### macOS 
<img width="573" alt="截屏2024-03-19 15 50 53" src="https://github.com/M0dEx/quincy/assets/17973891/34a0925e-c94f-4222-8edf-3d266fdf0351">
<img width="537" alt="截屏2024-03-19 15 51 51" src="https://github.com/M0dEx/quincy/assets/17973891/06f42daa-4c2d-41fa-a24a-512eb559022b">

**Comment by M0dEx** [comment]
What does the routing table look like on Windows and on MacOS?

Windows: `route print -4`
MacOS: `netstat -nr -f inet`

**Comment by xmh0511** [comment]
> What does the routing table look like on Windows and on MacOS?
> 
> Windows: `route print -4` MacOS: `netstat -nr -f inet`




### windows
<img width="820" alt="截屏2024-03-20 09 38 10" src="https://github.com/M0dEx/quincy/assets/17973891/d110e404-e2d4-43dd-a0de-3d1b06c3b0c4">

### macOS
<img width="706" alt="截屏2024-03-20 09 38 52" src="https://github.com/M0dEx/quincy/assets/17973891/3b1dded8-48ab-4b8c-9c02-1f3bab87c1ce">

**Comment by M0dEx** [comment]
Fortunately, I have the acces to a Windows and a MacOS system, so I will attempt to reproduce this locally and come up with a fix.

**Comment by M0dEx** [comment]
Seems this is not an issue with Quincy. Inbound ICMP is dropped by default on Windows. You have to enable the `Core Networking Diagnostics - ICMP Echo Request (ICMPv4-In)` rule for the ping from MacOS to work.

**Comment by xmh0511** [comment]
> Seems this is not an issue with Quincy. Inbound ICMP is dropped by default on Windows. You have to enable the `Core Networking Diagnostics - ICMP Echo Request (ICMPv4-In)` rule for the ping from MacOS to work.

That's the actual reason here. I ran the command 
> netsh firewall set icmpsetting 8

on my Windows, and it works now. Seems this issue has been fixed.
