### ISSUE TITLE
Read the configuration file from the environment

### ISSUE THREAD

**Issue by xmh0511** [M0dEx/quincy#59]
The `--config-path ./xxx.toml` is a bit tedious. Could we just read the config file from the environment where we invoke the program, and if we specify `--config-path`, then read file from the specified path.

**Comment by M0dEx** [comment]
I agree there should be a default, as having to specify the argument every time is a bit tedious. What should the default be, though?

- `client.toml` for the client
- `server.toml1 for the server
- `users` for the users tool

?

**Comment by xmh0511** [comment]
These default names are ok.
